[2020-08-25T11:06:26.549] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/user/permission?game=%E7%A9%BA%E7%BF%BC%E5%86%92%E9%99%A9%E5%9B%A2&username=admin
request client ip:  ::ffff:127.0.0.1
request query:  {"game":"空翼冒险团","username":"admin"}
response time: 1598324786548
err name: TypeError
err message: Cannot read property 'id' of undefined
err stack: TypeError: Cannot read property 'id' of undefined
    at _callee$ (H:\project\server\src\app\controllers\/user.js:21:47)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at findUser (H:\project\server\src\app\controllers\user.js:91:26)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
    at H:\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at H:\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (H:\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at H:\project\server\node_modules\koa-mount\index.js:52:32
    at next (H:\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee4$ (H:\project\server\src\middleware\/permission.js:91:17)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\project\server\src\middleware\/permission.js:78:2
    at next (H:\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\project\server\src\middleware\/interceptor.js:77:10)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
*************** error log end ***************

[2020-08-25T11:06:38.967] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/user/permission?game=%E7%A9%BA%E7%BF%BC%E5%86%92%E9%99%A9%E5%9B%A2&username=admin
request client ip:  ::1
request query:  {"game":"空翼冒险团","username":"admin"}
response time: 1598324798967
err name: TypeError
err message: Cannot read property 'id' of undefined
err stack: TypeError: Cannot read property 'id' of undefined
    at _callee$ (H:\project\server\src\app\controllers\/user.js:21:47)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at findUser (H:\project\server\src\app\controllers\user.js:91:26)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
    at H:\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at H:\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (H:\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at H:\project\server\node_modules\koa-mount\index.js:52:32
    at next (H:\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee4$ (H:\project\server\src\middleware\/permission.js:91:17)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at H:\project\server\src\middleware\/permission.js:78:2
    at next (H:\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\project\server\src\middleware\/interceptor.js:77:10)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
*************** error log end ***************

[2020-08-25T11:11:13.515] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598325073496
err name: TypeError
err message: MongoDb.findOne is not a function
err stack: TypeError: MongoDb.findOne is not a function
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:22:11)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CDKService.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CDKService.test (H:\project\server\src\app\service\cdk.js:106:22)
    at _callee2$ (H:\project\server\src\app\controllers\/cdk.js:17:36)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at test (H:\project\server\src\app\controllers\cdk.js:108:22)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
    at H:\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at H:\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (H:\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at H:\project\server\node_modules\koa-mount\index.js:52:32
    at next (H:\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee4$ (H:\project\server\src\middleware\/permission.js:91:17)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
*************** error log end ***************

[2020-08-25T11:13:30.510] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598325210509
err name: TypeError
err message: MongoDb.findOne is not a function
err stack: TypeError: MongoDb.findOne is not a function
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:22:11)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CDKService.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CDKService.test (H:\project\server\src\app\service\cdk.js:106:22)
    at _callee2$ (H:\project\server\src\app\controllers\/cdk.js:17:36)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at test (H:\project\server\src\app\controllers\cdk.js:108:22)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
    at H:\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at H:\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (H:\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at H:\project\server\node_modules\koa-mount\index.js:52:32
    at next (H:\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee4$ (H:\project\server\src\middleware\/permission.js:91:17)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
*************** error log end ***************

[2020-08-25T14:07:15.630] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598335635630
err name: TypeError
err message: MongoDb.findOne is not a function
err stack: TypeError: MongoDb.findOne is not a function
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:22:11)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CDKService.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CDKService.test (H:\project\server\src\app\service\cdk.js:106:22)
    at _callee2$ (H:\project\server\src\app\controllers\/cdk.js:17:36)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at test (H:\project\server\src\app\controllers\cdk.js:108:22)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
    at H:\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at H:\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (H:\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at H:\project\server\node_modules\koa-mount\index.js:52:32
    at next (H:\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee4$ (H:\project\server\src\middleware\/permission.js:91:17)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
*************** error log end ***************

[2020-08-25T14:14:14.209] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::ffff:127.0.0.1
request query:  {"1":"2"}
response time: 1598336054209
err name: OverwriteModelError
err message: Cannot overwrite `fancyguo` model once compiled.
err stack: OverwriteModelError: Cannot overwrite `fancyguo` model once compiled.
    at Mongoose.model (H:\project\server\node_modules\mongoose\lib\index.js:528:13)
    at mongodb.getConnection (H:\project\server\src\config\/mongoDBconfig.js:47:28)
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:27:23)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CDKService.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CDKService.test (H:\project\server\src\app\service\cdk.js:107:22)
    at _callee2$ (H:\project\server\src\app\controllers\/cdk.js:17:36)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at test (H:\project\server\src\app\controllers\cdk.js:108:22)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
    at H:\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at H:\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (H:\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at H:\project\server\node_modules\koa-mount\index.js:52:32
    at next (H:\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee4$ (H:\project\server\src\middleware\/permission.js:91:17)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
*************** error log end ***************

[2020-08-25T14:21:40.429] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598336500429
err name: TypeError
err message: node_model.insertOne is not a function
err stack: TypeError: node_model.insertOne is not a function
    at res (H:\project\server\src\config\/mongoDBconfig.js:66:15)
    at new Promise (<anonymous>)
    at mongodb._callee$ (H:\project\server\src\config\/mongoDBconfig.js:65:19)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at mongodb.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at mongodb.insertData (H:\project\server\src\config\mongoDBconfig.js:133:29)
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:27:27)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CDKService.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CDKService.test (H:\project\server\src\app\service\cdk.js:110:22)
    at _callee2$ (H:\project\server\src\app\controllers\/cdk.js:17:36)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at test (H:\project\server\src\app\controllers\cdk.js:108:22)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
*************** error log end ***************

[2020-08-25T14:22:51.867] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598336571867
err name: TypeError
err message: node_model.insertOne is not a function
err stack: TypeError: node_model.insertOne is not a function
    at res (H:\project\server\src\config\/mongoDBconfig.js:66:15)
    at new Promise (<anonymous>)
    at mongodb._callee$ (H:\project\server\src\config\/mongoDBconfig.js:65:19)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at mongodb.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at mongodb.insertData (H:\project\server\src\config\mongoDBconfig.js:133:29)
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:22:27)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CDKService.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CDKService.test (H:\project\server\src\app\service\cdk.js:110:22)
    at _callee2$ (H:\project\server\src\app\controllers\/cdk.js:17:36)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at test (H:\project\server\src\app\controllers\cdk.js:108:22)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
*************** error log end ***************

[2020-08-25T14:25:58.446] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598336758445
err name: TypeError
err message: node_model.insertOne is not a function
err stack: TypeError: node_model.insertOne is not a function
    at res (H:\project\server\src\config\/mongoDBconfig.js:58:15)
    at new Promise (<anonymous>)
    at mongodb._callee$ (H:\project\server\src\config\/mongoDBconfig.js:56:19)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at mongodb.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at mongodb.insertData (H:\project\server\src\config\mongoDBconfig.js:125:29)
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:22:27)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CDKService.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CDKService.test (H:\project\server\src\app\service\cdk.js:110:22)
    at _callee2$ (H:\project\server\src\app\controllers\/cdk.js:17:36)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at test (H:\project\server\src\app\controllers\cdk.js:108:22)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
*************** error log end ***************

[2020-08-25T14:28:30.168] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598336910167
err name: TypeError
err message: node_model.insertOne is not a function
err stack: TypeError: node_model.insertOne is not a function
    at res (H:\project\server\src\config\/mongoDBconfig.js:57:15)
    at new Promise (<anonymous>)
    at mongodb._callee$ (H:\project\server\src\config\/mongoDBconfig.js:56:19)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at mongodb.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at mongodb.insertData (H:\project\server\src\config\mongoDBconfig.js:124:29)
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:22:27)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CDKService.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CDKService.test (H:\project\server\src\app\service\cdk.js:110:22)
    at _callee2$ (H:\project\server\src\app\controllers\/cdk.js:17:36)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at test (H:\project\server\src\app\controllers\cdk.js:108:22)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
*************** error log end ***************

[2020-08-25T14:30:03.967] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598337003966
err name: TypeError
err message: node_model.insertOne is not a function
err stack: TypeError: node_model.insertOne is not a function
    at res (H:\project\server\src\config\/mongoDBconfig.js:57:16)
    at new Promise (<anonymous>)
    at mongodb._callee$ (H:\project\server\src\config\/mongoDBconfig.js:56:19)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at mongodb.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at mongodb.insertData (H:\project\server\src\config\mongoDBconfig.js:124:29)
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:22:27)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CDKService.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CDKService.test (H:\project\server\src\app\service\cdk.js:110:22)
    at _callee2$ (H:\project\server\src\app\controllers\/cdk.js:17:36)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at test (H:\project\server\src\app\controllers\cdk.js:108:22)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
*************** error log end ***************

[2020-08-25T15:19:28.137] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598339968136
err name: OverwriteModelError
err message: Cannot overwrite `fancyguo` model once compiled.
err stack: OverwriteModelError: Cannot overwrite `fancyguo` model once compiled.
    at Mongoose.model (H:\project\server\node_modules\mongoose\lib\index.js:528:13)
    at mongodb.getConnection (H:\project\server\src\config\/mongoDBconfig.js:45:28)
    at mongodb._callee3$ (H:\project\server\src\config\/mongoDBconfig.js:96:24)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at mongodb.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at mongodb.findOne (H:\project\server\src\config\mongoDBconfig.js:218:25)
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:22:27)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CDKService.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CDKService.test (H:\project\server\src\app\service\cdk.js:114:22)
    at _callee2$ (H:\project\server\src\app\controllers\/cdk.js:17:36)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at test (H:\project\server\src\app\controllers\cdk.js:108:22)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
*************** error log end ***************

[2020-08-25T15:26:30.561] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598340390561
err name: CastError
err message: Cast to ObjectId failed for value "{
  key: '111111111',
  isUse: false,
  plaform: '',
  channel: '',
  roleid: ''
}" at path "_id" for model "fancyguo"
err stack: CastError: Cast to ObjectId failed for value "{
  key: '111111111',
  isUse: false,
  plaform: '',
  channel: '',
  roleid: ''
}" at path "_id" for model "fancyguo"
    at model.Query.exec (H:\project\server\node_modules\mongoose\lib\query.js:4368:21)
    at model.Query.Query.findOne (H:\project\server\node_modules\mongoose\lib\query.js:2225:8)
    at Function.findOne (H:\project\server\node_modules\mongoose\lib\model.js:2157:13)
    at Function.findById (H:\project\server\node_modules\mongoose\lib\model.js:2095:15)
    at res (H:\project\server\src\config\/mongoDBconfig.js:94:14)
    at new Promise (<anonymous>)
    at mongodb._callee4$ (H:\project\server\src\config\/mongoDBconfig.js:93:19)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at mongodb.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at mongodb.findById (H:\project\server\src\config\mongoDBconfig.js:240:26)
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:22:27)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CDKService.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CDKService.test (H:\project\server\src\app\service\cdk.js:114:22)
    at _callee2$ (H:\project\server\src\app\controllers\/cdk.js:17:36)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
*************** error log end ***************

[2020-08-25T15:58:22.770] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598342302769
err name: TypeError
err message: mongoose.createCollection is not a function
err stack: TypeError: mongoose.createCollection is not a function
    at _callee5$ (H:\project\server\src\config\/mongoDBconfig.js:111:29)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at mongodb.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at mongodb.create (H:\project\server\src\config\mongoDBconfig.js:277:24)
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:22:27)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CDKService.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CDKService.test (H:\project\server\src\app\service\cdk.js:114:22)
    at _callee2$ (H:\project\server\src\app\controllers\/cdk.js:17:36)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at test (H:\project\server\src\app\controllers\cdk.js:108:22)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
    at H:\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
*************** error log end ***************

[2020-08-25T16:00:42.949] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598342442949
err name: TypeError
err message: mongoose.connect.createCollection is not a function
err stack: TypeError: mongoose.connect.createCollection is not a function
    at _callee5$ (H:\project\server\src\config\/mongoDBconfig.js:111:37)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at mongodb.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at mongodb.create (H:\project\server\src\config\mongoDBconfig.js:277:24)
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:22:27)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CDKService.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CDKService.test (H:\project\server\src\app\service\cdk.js:114:22)
    at _callee2$ (H:\project\server\src\app\controllers\/cdk.js:17:36)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at test (H:\project\server\src\app\controllers\cdk.js:108:22)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
    at H:\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
*************** error log end ***************

[2020-08-25T16:01:09.066] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::ffff:127.0.0.1
request query:  {"1":"2"}
response time: 1598342469065
err name: TypeError
err message: mongoose.Collection.createCollection is not a function
err stack: TypeError: mongoose.Collection.createCollection is not a function
    at _callee5$ (H:\project\server\src\config\/mongoDBconfig.js:111:40)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at mongodb.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at mongodb.create (H:\project\server\src\config\mongoDBconfig.js:277:24)
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:22:27)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CDKService.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CDKService.test (H:\project\server\src\app\service\cdk.js:114:22)
    at _callee2$ (H:\project\server\src\app\controllers\/cdk.js:17:36)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at test (H:\project\server\src\app\controllers\cdk.js:108:22)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
    at H:\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
*************** error log end ***************

[2020-08-25T16:02:12.775] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598342532775
err name: MongooseError
err message: You can't specify a new collection name in Model.createCollection.This is not like Connection.createCollection. Only options are accepted here.
err stack: MongooseError: You can't specify a new collection name in Model.createCollection.This is not like Connection.createCollection. Only options are accepted here.
    at Function.createCollection (H:\project\server\node_modules\mongoose\lib\model.js:1305:11)
    at _callee5$ (H:\project\server\src\config\/mongoDBconfig.js:116:26)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at mongodb.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at mongodb.create (H:\project\server\src\config\mongoDBconfig.js:283:24)
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:22:27)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CDKService.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CDKService.test (H:\project\server\src\app\service\cdk.js:114:22)
    at _callee2$ (H:\project\server\src\app\controllers\/cdk.js:17:36)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at test (H:\project\server\src\app\controllers\cdk.js:108:22)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
    at H:\project\server\node_modules\koa-router\lib\router.js:346:16
*************** error log end ***************

[2020-08-25T16:03:42.352] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598342622352
err name: MongoError
err message: Collection already exists. NS: fancyguo.test
err stack: MongoError: Collection already exists. NS: fancyguo.test
    at Connection.<anonymous> (H:\project\server\node_modules\mongodb\lib\core\connection\pool.js:451:61)
    at Connection.emit (events.js:315:20)
    at processMessage (H:\project\server\node_modules\mongodb\lib\core\connection\connection.js:452:10)
    at Socket.<anonymous> (H:\project\server\node_modules\mongodb\lib\core\connection\connection.js:621:15)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
*************** error log end ***************

[2020-08-25T16:23:59.809] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598343839809
err name: OverwriteModelError
err message: Cannot overwrite `test` model once compiled.
err stack: OverwriteModelError: Cannot overwrite `test` model once compiled.
    at Mongoose.model (H:\project\server\node_modules\mongoose\lib\index.js:528:13)
    at mongodb._callee5$ (H:\project\server\src\config\/mongoDBconfig.js:115:25)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at mongodb.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at mongodb.create (H:\project\server\src\config\mongoDBconfig.js:297:24)
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:22:27)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CDKService.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CDKService.test (H:\project\server\src\app\service\cdk.js:114:22)
    at _callee2$ (H:\project\server\src\app\controllers\/cdk.js:17:36)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at test (H:\project\server\src\app\controllers\cdk.js:108:22)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
    at H:\project\server\node_modules\koa-router\lib\router.js:346:16
*************** error log end ***************

[2020-08-25T18:30:28.896] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598351428896
err name: TypeError
err message: Invalid attempt to iterate non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
err stack: TypeError: Invalid attempt to iterate non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _createForOfIteratorHelper (H:\project\server\src\app\service\cdk.js:45:471)
    at _callee3$ (H:\project\server\src\app\service\cdk.js:166:29)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CDKService.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CDKService.test (H:\project\server\src\app\service\cdk.js:214:22)
    at _callee2$ (H:\project\server\src\app\controllers\/cdk.js:17:36)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at test (H:\project\server\src\app\controllers\cdk.js:108:22)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
    at H:\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at H:\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (H:\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at H:\project\server\node_modules\koa-mount\index.js:52:32
    at next (H:\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee4$ (H:\project\server\src\middleware\/permission.js:91:17)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
*************** error log end ***************

[2020-08-25T18:34:12.781] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598351652781
err name: OverwriteModelError
err message: Cannot overwrite `test` model once compiled.
err stack: OverwriteModelError: Cannot overwrite `test` model once compiled.
    at Mongoose.model (H:\project\server\node_modules\mongoose\lib\index.js:528:13)
    at mongodb.getConnection (H:\project\server\src\config\/mongoDBconfig.js:22:28)
    at mongodb._callee$ (H:\project\server\src\config\/mongoDBconfig.js:32:24)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at mongodb.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at mongodb.insertData (H:\project\server\src\config\mongoDBconfig.js:101:29)
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:54:18)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-08-25T18:34:47.426] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598351687425
err name: OverwriteModelError
err message: Cannot overwrite `test` model once compiled.
err stack: OverwriteModelError: Cannot overwrite `test` model once compiled.
    at Mongoose.model (H:\project\server\node_modules\mongoose\lib\index.js:528:13)
    at mongodb.getConnection (H:\project\server\src\config\/mongoDBconfig.js:22:28)
    at mongodb._callee$ (H:\project\server\src\config\/mongoDBconfig.js:32:24)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at mongodb.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at mongodb.insertData (H:\project\server\src\config\mongoDBconfig.js:101:29)
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:54:18)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-08-25T18:36:43.583] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598351803582
err name: OverwriteModelError
err message: Cannot overwrite `test` model once compiled.
err stack: OverwriteModelError: Cannot overwrite `test` model once compiled.
    at Mongoose.model (H:\project\server\node_modules\mongoose\lib\index.js:528:13)
    at mongodb.getConnection (H:\project\server\src\config\/mongoDBconfig.js:22:28)
    at mongodb._callee$ (H:\project\server\src\config\/mongoDBconfig.js:32:24)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at mongodb.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at mongodb.insertData (H:\project\server\src\config\mongoDBconfig.js:101:29)
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:54:18)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-08-25T18:45:10.361] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/cdk/test?1=2
request client ip:  ::1
request query:  {"1":"2"}
response time: 1598352310360
err name: OverwriteModelError
err message: Cannot overwrite `test` model once compiled.
err stack: OverwriteModelError: Cannot overwrite `test` model once compiled.
    at Mongoose.model (H:\project\server\node_modules\mongoose\lib\index.js:528:13)
    at mongodb.getConnection (H:\project\server\src\config\/mongoDBconfig.js:22:28)
    at mongodb._callee7$ (H:\project\server\src\config\/mongoDBconfig.js:151:24)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at mongodb.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at mongodb.insertManyData (H:\project\server\src\config\mongoDBconfig.js:384:32)
    at _callee2$ (H:\project\server\src\app\service\/cdk.js:57:17)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CDKService.<anonymous> (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CDKService.test (H:\project\server\src\app\service\cdk.js:181:22)
    at _callee2$ (H:\project\server\src\app\controllers\/cdk.js:17:36)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at test (H:\project\server\src\app\controllers\cdk.js:108:22)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
*************** error log end ***************

