[2020-08-20T17:39:04.422] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/cdk/createcdk
request client ip:  ::ffff:127.0.0.1
request body: 
{"name":"1","type":"1","cdkkey":"GxP1kyij9n","quantity":1,"plaform":["1"],"channel":["小米"],"takeEffectTime":"2020-08-25T16:00:00.000Z","failureTime":"2020-08-26T16:00:00.000Z","title":"1","text":"1","annexList":[{"annexName":["特殊道具","9001"],"annexNumber":11,"id":0}],"gameid":"1"}
response time: 1597916344421
err name: ReferenceError
err message: CDKService is not defined
err stack: ReferenceError: CDKService is not defined
    at _callee$ (H:\project\server\src\app\controllers\cdk.js:61:17)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at createcdk (H:\project\server\src\app\controllers\cdk.js:76:27)
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at next (H:\project\server\node_modules\koa-compose\index.js:45:18)
    at H:\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (H:\project\server\node_modules\koa-compose\index.js:44:32)
    at H:\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (H:\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (H:\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at H:\project\server\node_modules\koa-mount\index.js:52:32
    at next (H:\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at _callee$ (H:\project\server\src\middleware\/auth.js:40:9)
    at tryCatch (H:\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

